#!/bin/bash

DOMAIN_ARR=$(echo $DOMAIN | tr ";" "\n")

COUNTER=0
for i in $DOMAIN_ARR
do
  NAME_ARR[$COUNTER]=$(echo $i | tr "," "\n" | head -1 )

  PARAMS=""
  for j in $(echo $i | tr "," "\n")
  do
    PARAMS="$PARAMS -d $j"
  done

  PARAM_ARR[$COUNTER]="$PARAMS"

  let COUNTER+=1
done

RESTART_ARR=$(echo $RESTART | tr ";" "\n")
COUNTER=0
for i in $RESTART_ARR
do
  CONTAINER_ARR[$COUNTER]=$(echo $i | tr "," " ")
  let COUNTER+=1
done

for (( i=0; i<${#PARAM_ARR[@]}; i++ ))
do
  mv ${CERTS_DIR}chain_${NAME_ARR[$i]}.pem ${CERTS_DIR}chain.pem
  mv ${CERTS_DIR}cert_${NAME_ARR[$i]}.pem ${CERTS_DIR}cert.pem
  mv ${CERTS_DIR}key_${NAME_ARR[$i]}.pem ${CERTS_DIR}key.pem

  docker run -v $CERTS_DIR:/certs/ --rm -it -p $LISTEN_PORT:80 \
    --name $SERVER_NAME \
    m3adow/letsencrypt-simp_le  \
    --email $EMAIL -f account_key.json -f chain.pem -f cert.pem -f key.pem \
    ${PARAM_ARR[$i]}

  STATUS=$?

  mv ${CERTS_DIR}chain.pem ${CERTS_DIR}chain_${NAME_ARR[$i]}.pem
  mv ${CERTS_DIR}cert.pem ${CERTS_DIR}cert_${NAME_ARR[$i]}.pem
  mv ${CERTS_DIR}key.pem ${CERTS_DIR}key_${NAME_ARR[$i]}.pem

  if [ $STATUS = 0 ]
  then
    docker restart ${CONTAINER_ARR[$i]}

    # to limit request rate
    sleep 60
  fi
done
