#!/bin/bash

echo 'Start'

FILES=$(ls /etc/simp_le-auto.d/)

COUNTER=0
for i in $FILES
do
  readarray CONTENT < /etc/simp_le-auto.d/$i
  NAME_ARR[$COUNTER]=$(echo ${CONTENT[0]} | tr "," "\n" | head -1 )
  CONTAINER_ARR[$COUNTER]=$(echo ${CONTENT[1]} | tr "," " ")

  PARAMS=""
  for j in $(echo ${CONTENT[0]} | tr "," "\n")
  do
    PARAMS="$PARAMS -d $j"
  done

  PARAM_ARR[$COUNTER]="$PARAMS"

  let COUNTER+=1
done

for (( i=0; i<${#PARAM_ARR[@]}; i++ ))
do
  echo "Try ${NAME_ARR[$i]}"

  docker $DOCKER_SIMP_LE_ARGS rm $SERVER_NAME

  mv ${CERTS_DIR}chain_${NAME_ARR[$i]}.pem ${CERTS_DIR}chain.pem
  mv ${CERTS_DIR}cert_${NAME_ARR[$i]}.pem ${CERTS_DIR}cert.pem
  mv ${CERTS_DIR}key_${NAME_ARR[$i]}.pem ${CERTS_DIR}key.pem
  mv ${CERTS_DIR}fullchain_${NAME_ARR[$i]}.pem ${CERTS_DIR}fullchain.pem

  docker $DOCKER_SIMP_LE_ARGS create -p $LISTEN_PORT:80 \
    --name $SERVER_NAME $DOCKER_RUN_SIMP_LE_ARGS \
    m3adow/letsencrypt-simp_le \
    --tos_sha256 6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221 \
    --email $EMAIL \
    -f account_key.json -f chain.pem -f cert.pem -f key.pem -f fullchain.pem \
    ${PARAM_ARR[$i]}

  STATUS=$?

  docker $DOCKER_SIMP_LE_ARGS cp ${CERTS_DIR}account_key.json $SERVER_NAME:/certs/account_key.json
  docker $DOCKER_SIMP_LE_ARGS cp ${CERTS_DIR}chain.pem $SERVER_NAME:/certs/chain.pem
  docker $DOCKER_SIMP_LE_ARGS cp ${CERTS_DIR}cert.pem $SERVER_NAME:/certs/cert.pem
  docker $DOCKER_SIMP_LE_ARGS cp ${CERTS_DIR}key.pem $SERVER_NAME:/certs/key.pem
  docker $DOCKER_SIMP_LE_ARGS cp ${CERTS_DIR}fullchain.pem $SERVER_NAME:/certs/fullchain.pem

  docker $DOCKER_SIMP_LE_ARGS start $SERVER_NAME

  docker $DOCKER_SIMP_LE_ARGS cp $SERVER_NAME:/certs/account_key.json ${CERTS_DIR}account_key.json
  docker $DOCKER_SIMP_LE_ARGS cp $SERVER_NAME:/certs/chain.pem ${CERTS_DIR}chain.pem
  docker $DOCKER_SIMP_LE_ARGS cp $SERVER_NAME:/certs/cert.pem ${CERTS_DIR}cert.pem
  docker $DOCKER_SIMP_LE_ARGS cp $SERVER_NAME:/certs/key.pem ${CERTS_DIR}key.pem
  docker $DOCKER_SIMP_LE_ARGS cp $SERVER_NAME:/certs/fullchain.pem ${CERTS_DIR}fullchain.pem

  mv ${CERTS_DIR}chain.pem ${CERTS_DIR}chain_${NAME_ARR[$i]}.pem
  mv ${CERTS_DIR}cert.pem ${CERTS_DIR}cert_${NAME_ARR[$i]}.pem
  mv ${CERTS_DIR}key.pem ${CERTS_DIR}key_${NAME_ARR[$i]}.pem
  mv ${CERTS_DIR}fullchain.pem ${CERTS_DIR}fullchain_${NAME_ARR[$i]}.pem

  if [ $STATUS = 0 ]
  then
    if [ -n "${CONTAINER_ARR[$i]}" ]
    then
      docker $DOCKER_SIMP_LE_ARGS restart ${CONTAINER_ARR[$i]}
    fi

    # to limit request rate
    sleep 60
  fi

  docker $DOCKER_SIMP_LE_ARGS rm $SERVER_NAME
done

echo 'Finish'
